[package]
name = "three"
version = "0.1.0"
authors = ["Dzmitry Malyshau <kvarkus@gmail.com>"]

[lib]

[features]
default = ["opengl"]
"opengl" = ["gfx_device_gl", "gfx_window_glutin", "glutin"]

[dependencies]
cgmath = "0.12"
gfx = "0.14"
winit = "0.5"
gfx_device_gl = { version = "0.13", optional = true }
gfx_window_glutin = { version = "0.14", optional = true }
glutin = { version = "0.7", optional = true }
