[package]
name = "three"
version = "0.1.0"
authors = ["Dzmitry Malyshau <kvarkus@gmail.com>"]

[lib]

[features]
default = ["opengl"]
"opengl" = ["gfx_device_gl", "gfx_window_glutin", "glutin"]

[dependencies]
cgmath = "0.14"
froggy = "0.3"
genmesh = "0.4"
gfx = "0.15"
winit = "0.6"
# OpenGL
gfx_device_gl = { version = "0.14", optional = true }
gfx_window_glutin = { version = "0.16", optional = true }
glutin = { version = "0.8", optional = true }
